name: Merging stage to prod

on:
  push:
    branches: [ "staging" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Merge on Staging
        uses: robotology/gh-action-nightly-merge@v1.3.3
        with:
          stable_branch: 'staging'
          development_branch: 'production'
          allow_ff: true
          allow_forks: true
          user_name: Auto merge from Staging to Prod
        env:
          GITHUB_TOKEN: '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'
